# Generated by Django 5.1.1 on 2024-10-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutcars', '0002_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
