# Generated by Django 5.1.1 on 2024-10-04 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutcars', '0005_alter_car_owner_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutcars.car'),
        ),
    ]
